### ISSUE TITLE
How do I run generated jar..?

### ISSUE THREAD

**Issue by devsaik** [DeviantArt/kafka-connect-s3#4]
Once the jar is built locally on mac. With all the tests passing. How do I run this App?. There are no instructions specific to it in Docs. As I can see local-run.sh is missing

Sorry for confusion:  I am running this command: connect-standalone /usr/local/etc/kafka/connect-standalone.properties connect-s3-sink.properties 
Unfotunately I get this error:Error: Could not find or load main class org.apache.kafka.connect.cli.ConnectStandalone

**Comment by samitpatel** [comment]
Hey devsaik, 
I am also running into same issue. Can you please share what workaround or fix did you use? 

Thanks.

**Comment by devsaik** [comment]
I think my pull request with more exhaustive  instructions is already merged into readme. Post ur error log that might help me in understanding ur issue
